### ISSUE TITLE
Add tests for "Courses" Part of the app

### ISSUE THREAD

**Issue by rebeccarothschild** [wsu-cpts489-fa20/bp-kliks#30]
Acceptance criteria:

- [x] Test courses table (verify ui for different user types and button functionality)

- [x] Test create, delete, update course

- [x] Test students table (verify ui for different user types and button functionality including upload)

- [x]  Test create, delete, update students

**Comment by HatchedCode** [comment]
There are some features such as delete and edit courses that are not yet completed, moving this into Milestone 4. @marcoarceo
