### ISSUE TITLE
As a student, I want to receive feedback that my submission was successful so that I ensure that my response will receive credit and I don’t panic about not receiving credit.

### ISSUE THREAD

**Issue by rebeccarothschild** [wsu-cpts489-fa20/bp-kliks#5]

**Comment by Danejerosa1111** [comment]
- [ ]  Add a Dialogue box that comes up when the user selects "Ok" that confirms answering the question.
- [ ]  Add an alert message to the user that they have answered the question after confirming answer.
- [ ]  Update MongoDB or Local Storage when users answer is sent.

**Comment by marcoarceo** [comment]
Need to implement a student UI and a section where the student can answer questions so this issue can be relevant

**Comment by marcoarceo** [comment]
This issue is going to be rolled into next milestone

**Comment by HatchedCode** [comment]
Won't have time to complete.
