### ISSUE TITLE
As an Instructor, I want to be able to create different type of questions for students so that I can receive different responses to different types of questions.

### ISSUE THREAD

**Issue by rebeccarothschild** [wsu-cpts489-fa20/bp-kliks#6]

**Comment by Danejerosa1111** [comment]
- [x] Make a "Create question tab" that has a dialogue pop up.
- [x] Make a multiple choice question style.
- [x] Make a short answer tab.
- [x] Make a true or false tab.
- [x] Make an essay question tab.

**Comment by HatchedCode** [comment]
This issue has been completed
