### ISSUE TITLE
As a student, I want to be able to easily access Kliks through OSBLE that way my account is verified with the class so that only classmates can submit responses.

### ISSUE THREAD

**Issue by rebeccarothschild** [wsu-cpts489-fa20/bp-kliks#7]

**Comment by marcoarceo** [comment]
- [ ] Have to provide a wsu.edu email address to be verified
- [ ] Integrate Kliks website to the OSBLE website (link or directly)

**Comment by chundhau** [comment]
I recommend against supporting this user story. Do not rely on OSBLE for authentication. Instead, your authentication and user management system should be self-contained.
