### ISSUE TITLE
As a student or Instructor, I want to be able to create an account so I can keep the same configurations each time I use the app and access the proper surveys.

### ISSUE THREAD

**Issue by rebeccarothschild** [wsu-cpts489-fa20/bp-kliks#8]

**Comment by marcoarceo** [comment]
- [x] Can provide a picture of myself or a default image
- [x] Can use an email address as my id/username
- [x] Can use my name as a display name
- [x] Can store information into my account such as polls and their answers
- [x] Can create a password that will be specific to my account
- [x] Can have a security question and answer that will help my reset my password if lost/forgotten
- [x] New account is either a student or instructor account

**Comment by HatchedCode** [comment]
We were not able to complete this issue during milestone 2 because we ran out time, but we will be able to complete it during our next sprint cycle. So I am moving it to Milestone 3.
